# Generated by Django 6.0.3 on 2026-05-30 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Kategoriebild')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Zutat')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Rezeptname')),
                ('servings', models.PositiveSmallIntegerField(default=2, help_text='Anzahl Portionen', verbose_name='Portionen')),
                ('preparation_length', models.PositiveSmallIntegerField(help_text='Zeit in Minuten', verbose_name='Zubereitungszeit (Minuten)')),
                ('instructions', models.TextField(verbose_name='Zubereitung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 'Schlecht'), (2, 'Mittel'), (3, 'Sehr gut')], default=2, help_text='Bewertung von 1 (schlecht) bis 3 (sehr gut)')),
                ('categories', models.ManyToManyField(blank=True, related_name='recipes', to='core.category', verbose_name='Kategorien')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipe_images/', verbose_name='Bild')),
                ('is_title', models.BooleanField(default=False, verbose_name='Titelbild')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.recipe', verbose_name='Rezept')),
            ],
            options={
                'ordering': ['-is_title', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Menge', max_digits=6, verbose_name='Menge')),
                ('unit', models.CharField(help_text='Einheit, z.B. g, ml, TL', max_length=16, verbose_name='Einheit')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='core.ingredient', verbose_name='Zutat')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='core.recipe', verbose_name='Rezept')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='core.RecipeIngredient', to='core.ingredient', verbose_name='Zutaten'),
        ),
    ]
